### ISSUE TITLE
[feat] - header 영역 : 좌표에 따른 주소 정보 노출 작업 관련 이슈

### ISSUE THREAD

**Issue by jigico** [wheres-my-toilet/wheres-my-toilet#6]
📕 Issue Feature 
현재의 kakao map api로는 위도/경도로 주소로 변환할 수 없어서 kakao rest api 키 발급이 필요합니다.

🧾Todo
- [x] rest api key 발급
- [x] 위도/경도 -> 주소 변환 작업

참고했던 문서
https://developers.kakao.com/docs/latest/ko/local/dev-guide#coord-to-address-sample

**Comment by ketchup0211** [comment]
그 외 기능들도 자주 쓸 수 있는 여지가 있으니 KAKAO REST API KEY 발급 받으면 좋을 것 같아요!
